modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/SuperScary/HotSwap/issues"
license = "The MIT License"

[[mods]]
modId = "hotswap"
version = "${version}"
displayName = "HotSwap"
authors = "SuperScary"
description = '''
Auto swapping tool for Minecraft.
'''
logoFile = "assets/hotswapneo/logo.png"

[[dependencies.hotswap]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hotswap]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hotswap]]
modId = "architectury"
type = "required"
versionRange = "[12.1.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "hotswap.mixins.json"
